// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    partial class AirportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Movement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dst")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlainOnMoveId")
                        .HasColumnType("int");

                    b.Property<int?>("Src")
                        .HasColumnType("int");

                    b.HasKey("MovementId");

                    b.HasIndex("PlainOnMoveId");

                    b.ToTable("Movement");
                });

            modelBuilder.Entity("Models.Plane", b =>
                {
                    b.Property<int>("PlaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dst")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedOnDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FinishedProcess")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("bit");

                    b.Property<int>("PlanesPurpose")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedOnSystemDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SerialID")
                        .HasColumnType("int");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<bool>("StartedProcess")
                        .HasColumnType("bit");

                    b.HasKey("PlaneId");

                    b.ToTable("Plane");
                });

            modelBuilder.Entity("Models.Movement", b =>
                {
                    b.HasOne("Models.Plane", "PlainOnMove")
                        .WithMany()
                        .HasForeignKey("PlainOnMoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlainOnMove");
                });
#pragma warning restore 612, 618
        }
    }
}
